import { useMemo, useState } from 'react';
import { Camera, ChevronRight, Mic, Search, Sparkles, Tag, Trash2, WandSparkles } from 'lucide-react';
import { useProjects } from '../lib/projectStore';

type Walkthrough={id:string;projectId:string;createdAt:string;room:string;tags:number;notes:string};
const walkKey='aurelium.walkthroughs.web.v1';
function loadWalks():Walkthrough[]{try{return JSON.parse(localStorage.getItem(walkKey)||'[]')}catch{return[]}}
export function Estimator(){
 const projects=useProjects(); const [search,setSearch]=useState(''); const [selected,setSelected]=useState(projects[0]?.id??''); const [walks,setWalks]=useState<Walkthrough[]>(loadWalks());
 const project=projects.find(p=>p.id===selected); const matches=useMemo(()=>search?projects.filter(p=>`${p.name} ${p.clientName} ${p.address}`.toLowerCase().includes(search.toLowerCase())).slice(0,6):[],[projects,search]);
 const projectWalks=walks.filter(w=>w.projectId===selected); const saveWalks=(n:Walkthrough[])=>{setWalks(n);localStorage.setItem(walkKey,JSON.stringify(n))};
 return <div className="page estimator-page"><header className="page-header"><div><p className="eyebrow">AI-assisted</p><h1>Smart Estimate</h1><p>Every walkthrough starts from a known project and keeps its scan, narration, evidence, and estimate context together.</p></div></header>
 <section className="project-search-panel"><p className="eyebrow">Walkthrough project</p><label className="search project-search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search every job, client, or address…"/></label>{matches.length>0&&<div className="search-results">{matches.map(p=><button key={p.id} onClick={()=>{setSelected(p.id);setSearch('')}}><span><strong>{p.name}</strong><small>{p.clientName} · {p.address}</small></span><ChevronRight size={18}/></button>)}</div>}{project&&<div className="selected-project"><span><strong>{project.name}</strong><small>{project.clientName} · {project.address}</small></span><b>SELECTED</b></div>}</section>
 <div className="estimator-layout"><section className="capture-panel"><div className="capture-hero"><div className="capture-orb"><Camera size={28}/></div><div><span className="live-dot">Native iOS</span><h2>One guided walkthrough</h2><p>The iOS scanner now combines RoomPlan spatial capture, live narration, tagged evidence photos, and scan video review in one field experience.</p></div></div><div className="capture-actions"><div className="capture-action"><Mic/><span><strong>Narrate while scanning</strong><small>Damage, prep, furniture, access, exclusions</small></span><ChevronRight/></div><div className="capture-action"><Tag/><span><strong>Tag evidence instantly</strong><small>DAMAGE · REMOVE · DO NOT DISTURB · COVER · PAINT</small></span><ChevronRight/></div><div className="capture-action"><WandSparkles/><span><strong>Review before scope</strong><small>Video + tagged captures + transcript + measurements</small></span><ChevronRight/></div></div><div className="callout"><strong>Use the iOS app for spatial capture.</strong><span>The web app manages the same job records and walkthrough history; browser AR is intentionally not treated as equivalent to RoomPlan.</span></div></section>
 <section className="panel estimate-sheet"><div className="section-title"><div><p className="eyebrow">Walkthrough history</p><h2>{project?.name??'Choose a project'}</h2></div></div>{projectWalks.length===0?<div className="compact-empty"><Sparkles/><strong>No walkthroughs yet</strong><span>Start the first scan from the iOS app.</span></div>:<div className="room-list">{projectWalks.map(w=><div className="room-row" key={w.id}><div><strong>{w.room}</strong><span>{new Date(w.createdAt).toLocaleString()} · {w.tags} tagged captures</span></div><button aria-label="Delete walkthrough" onClick={()=>saveWalks(walks.filter(x=>x.id!==w.id))}><Trash2 size={17}/></button></div>)}</div>}</section></div></div>
}
