import { useEffect, useMemo, useState } from 'react';
import { BrainCircuit, Camera, ChevronRight, FileSearch2, Mic, Pencil, Search, Sparkles, Tag, Trash2, WandSparkles } from 'lucide-react';
import { useProjects } from '../lib/projectStore';
import { supabase } from '../lib/supabase';

type ScopeLine={kind:'walls'|'doors'|'windows'|'trim'|'ceiling';enabled:boolean;quantity:number;productionRate:number};
type Walkthrough={id:string;projectId:string;createdAt:string;room:string;tags:number;notes:string;archivedAt?:string|null;scopeLines?:ScopeLine[]};
const walkKey='aurelium.walkthroughs.web.v1';
type BlueprintRecord={id:string;project_id:string;file_name:string;proposal_ready:boolean;paintable_square_feet:number;labor_hours:number;status:string;created_at:string};
const defaults:ScopeLine[]=[{kind:'walls',enabled:true,quantity:0,productionRate:150},{kind:'doors',enabled:false,quantity:0,productionRate:2},{kind:'windows',enabled:false,quantity:0,productionRate:2},{kind:'trim',enabled:false,quantity:0,productionRate:50},{kind:'ceiling',enabled:false,quantity:0,productionRate:125}];
function loadWalks():Walkthrough[]{try{return JSON.parse(localStorage.getItem(walkKey)||'[]')}catch{return[]}}
const labor=(s:ScopeLine)=>s.enabled&&s.productionRate>0?s.quantity/s.productionRate:0;
export function Estimator(){
 const projects=useProjects(); const [search,setSearch]=useState(''); const [selected,setSelected]=useState(projects[0]?.id??''); const [walks,setWalks]=useState<Walkthrough[]>(loadWalks()); const [editing,setEditing]=useState<Walkthrough|null>(null);
 const project=projects.find(p=>p.id===selected); const matches=useMemo(()=>search?projects.filter(p=>`${p.name} ${p.clientName} ${p.address}`.toLowerCase().includes(search.toLowerCase())).slice(0,6):[],[projects,search]);
 const [blueprints,setBlueprints]=useState<BlueprintRecord[]>([]);
 useEffect(()=>{let cancelled=false;const client=supabase;if(!client||!selected){setBlueprints([]);return;}void client.from('blueprint_estimates').select('id,project_id,file_name,proposal_ready,paintable_square_feet,labor_hours,status,created_at').eq('project_id',selected).order('created_at',{ascending:false}).limit(12).then(({data})=>{if(!cancelled)setBlueprints((data??[]) as BlueprintRecord[])});return()=>{cancelled=true}},[selected]);
 const projectWalks=walks.filter(w=>w.projectId===selected); const saveWalks=(n:Walkthrough[])=>{setWalks(n);localStorage.setItem(walkKey,JSON.stringify(n))};
 const saveEdit=(w:Walkthrough)=>{saveWalks(walks.map(x=>x.id===w.id?w:x));setEditing(null)};
 return <div className="page estimator-page"><header className="page-header"><div><p className="eyebrow">Focused workspace</p><h1>Smart Estimate</h1><p>Scan on iOS, then review and edit scope assumptions without rescanning. Archived walkthroughs remain protected.</p></div></header>
 <section className="project-search-panel"><p className="eyebrow">Walkthrough project</p><label className="search project-search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search every job, client, or address…"/></label>{matches.length>0&&<div className="search-results">{matches.map(p=><button key={p.id} onClick={()=>{setSelected(p.id);setSearch('')}}><span><strong>{p.name}</strong><small>{p.clientName} · {p.address}</small></span><ChevronRight size={18}/></button>)}</div>}{project&&<div className="selected-project"><span><strong>{project.name}</strong><small>{project.clientName} · {project.address}</small></span><b>SELECTED</b></div>}</section>
 <div className="estimator-layout"><section className="capture-panel"><div className="capture-hero"><div className="capture-orb"><Camera size={28}/></div><div><span className="live-dot">Smart Scanner v2</span><h2>One scanner. Interior + exterior engines.</h2><p>Interior uses RoomPlan where it is strongest. Exterior uses ARKit/LiDAR surface reconstruction plus visual opening candidates. Both feed the same estimate and correction history.</p></div></div><div className="capture-actions"><div className="capture-action"><BrainCircuit/><span><strong>Teach Scanner</strong><small>Confirm or add missed doors, windows, openings and roof slopes; corrections become labeled training examples</small></span><ChevronRight/></div><div className="capture-action"><Mic/><span><strong>Narrate while scanning</strong><small>Damage, prep, furniture, access, exclusions</small></span><ChevronRight/></div><div className="capture-action"><Tag/><span><strong>Tag evidence instantly</strong><small>DAMAGE · REMOVE · DO NOT DISTURB · COVER · PAINT</small></span><ChevronRight/></div></div></section>
 <section className="panel estimate-sheet"><div className="section-title"><div><p className="eyebrow">Blueprint Estimate</p><h2>Plan intelligence</h2></div><FileSearch2/></div><p>Import PDF/image plans in the native Smart Estimate workspace. Aurelium reads sheets, finish schedules, scales and explicit dimensions, then blocks proposal generation when required measurements are unresolved.</p>{blueprints.length===0?<div className="compact-empty"><FileSearch2/><strong>No blueprint analyses yet</strong><span>Open Smart Estimate on iOS and choose Blueprint Estimate.</span></div>:<div className="room-list">{blueprints.map(b=><div className="room-row" key={b.id}><div><strong>{b.file_name}</strong><span>{Math.round(b.paintable_square_feet)} sf · {b.labor_hours.toFixed(1)} hr · {new Date(b.created_at).toLocaleDateString()}</span></div><b>{b.proposal_ready?'READY':'REVIEW'}</b></div>)}</div>}</section>
 <section className="panel estimate-sheet"><div className="section-title"><div><p className="eyebrow">Walkthrough history</p><h2>{project?.name??'Choose a project'}</h2></div></div>{projectWalks.length===0?<div className="compact-empty"><Sparkles/><strong>No walkthroughs yet</strong><span>Start the first scan from the iOS app.</span></div>:<div className="room-list">{projectWalks.map(w=><div className="room-row" key={w.id}><div><strong>{w.room}</strong><span>{new Date(w.createdAt).toLocaleString()} · {w.tags} tagged captures{w.archivedAt?' · Finalized':''}</span></div><div className="admin-row-actions"><button className="button secondary" disabled={!!w.archivedAt} onClick={()=>setEditing({...w,scopeLines:w.scopeLines?.length?w.scopeLines:defaults.map(x=>({...x}))})}><Pencil size={16}/>Edit</button><button aria-label="Delete walkthrough" disabled={!!w.archivedAt} onClick={()=>saveWalks(walks.filter(x=>x.id!==w.id))}><Trash2 size={17}/></button></div></div>)}</div>}</section></div>{editing&&<WalkthroughEditor value={editing} onCancel={()=>setEditing(null)} onSave={saveEdit}/>}</div>
}
function WalkthroughEditor({value,onCancel,onSave}:{value:Walkthrough;onCancel:()=>void;onSave:(w:Walkthrough)=>void}){const [d,setD]=useState(value);const lines=d.scopeLines||defaults;const update=(i:number,p:Partial<ScopeLine>)=>setD({...d,scopeLines:lines.map((x,j)=>j===i?{...x,...p}:x)});const total=lines.reduce((n,x)=>n+labor(x),0);return <div className="modal-backdrop"><div className="modal-card walkthrough-editor"><div className="modal-head"><div><p className="eyebrow">Non-destructive edit</p><h2>Edit walkthrough</h2></div><button className="icon-button" onClick={onCancel}>×</button></div><div className="form-grid"><label className="wide">Room name<input value={d.room} onChange={e=>setD({...d,room:e.target.value})}/></label><label className="wide">Notes<textarea value={d.notes||''} onChange={e=>setD({...d,notes:e.target.value})}/></label></div><div className="scope-editor">{lines.map((s,i)=><div className="scope-edit-row" key={s.kind}><label className="admin-checkbox"><input type="checkbox" checked={s.enabled} onChange={e=>update(i,{enabled:e.target.checked})}/><span>{s.kind[0].toUpperCase()+s.kind.slice(1)}</span></label><label>Quantity<input type="number" min="0" step="0.1" value={s.quantity} onChange={e=>update(i,{quantity:Number(e.target.value)})}/></label><label>Production rate<input type="number" min="0.01" step="0.1" value={s.productionRate} onChange={e=>update(i,{productionRate:Number(e.target.value)})}/></label><strong>{labor(s).toFixed(2)} hr</strong></div>)}</div><div className="modal-actions"><strong className="walk-labor">Room labor: {total.toFixed(2)} hr</strong><button className="button secondary" onClick={onCancel}>Cancel</button><button className="button primary" disabled={!d.room.trim()||lines.some(x=>x.enabled&&x.productionRate<=0)} onClick={()=>onSave(d)}>Save & recalculate</button></div></div></div>}
