import { useState } from 'react';
import { Filter, Pencil, Plus, Search, Trash2, X } from 'lucide-react';
import { StatusPill } from '../components/StatusPill';
import type { Project, ProjectStatus } from '../types/domain';
import { deleteProject, upsertProject, useProjects } from '../lib/projectStore';

const blank=():Project=>({id:crypto.randomUUID(),name:'',address:'',clientName:'',status:'estimating',trade:'painting',progress:0,crewCount:0,updatedAt:'Today'});
export function Projects(){
 const projects=useProjects(); const [search,setSearch]=useState(''); const [editing,setEditing]=useState<Project|null>(null);
 const filtered=projects.filter(p=>`${p.name} ${p.clientName} ${p.address}`.toLowerCase().includes(search.toLowerCase()));
 return <div className="page"><header className="page-header"><div><p className="eyebrow">Operations</p><h1>Projects</h1><p>One source of truth from lead through closeout.</p></div><button className="button primary" onClick={()=>setEditing(blank())}><Plus size={18}/>New project</button></header>
 <div className="toolbar"><label className="search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search projects, clients, addresses…"/></label><button className="button secondary"><Filter size={17}/>Filter</button></div>
 <div className="table-wrap"><table><thead><tr><th>Project</th><th>Status</th><th>Trade</th><th>Progress</th><th>Crew</th><th>Updated</th><th></th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><strong>{p.name}</strong><span>{p.clientName}<br/>{p.address}</span></td><td><StatusPill status={p.status}/></td><td className="capitalize">{p.trade}</td><td><div className="progress"><i style={{width:`${p.progress}%`}}/></div><span>{p.progress}%</span></td><td>{p.crewCount}</td><td>{p.updatedAt}</td><td><div className="row-actions"><button aria-label="Edit project" onClick={()=>setEditing(p)}><Pencil size={16}/></button><button aria-label="Delete project" onClick={()=>{if(confirm(`Delete ${p.name}?`)) deleteProject(p.id)}}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>
 {editing&&<ProjectModal project={editing} close={()=>setEditing(null)}/>}</div>
}
function ProjectModal({project,close}:{project:Project;close:()=>void}){const [draft,setDraft]=useState(project); const set=(k:keyof Project,v:string|number)=>setDraft(d=>({...d,[k]:v})); return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal-card"><div className="modal-head"><div><p className="eyebrow">Job record</p><h2>{project.name?'Edit project':'New project'}</h2></div><button className="icon-button" onClick={close}><X/></button></div><div className="form-grid"><label>Project name<input value={draft.name} onChange={e=>set('name',e.target.value)}/></label><label>Client<input value={draft.clientName} onChange={e=>set('clientName',e.target.value)}/></label><label className="wide">Address / location<input value={draft.address} onChange={e=>set('address',e.target.value)}/></label><label>Status<select value={draft.status} onChange={e=>set('status',e.target.value as ProjectStatus)}>{['lead','estimating','scheduled','active','paused','complete','archived'].map(x=><option key={x}>{x}</option>)}</select></label><label>Trade<select value={draft.trade} onChange={e=>set('trade',e.target.value as Project['trade'])}>{['painting','general','drywall','flooring','roofing','other'].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="modal-actions"><button className="button secondary" onClick={close}>Cancel</button><button className="button primary" disabled={!draft.name.trim()} onClick={()=>{upsertProject({...draft,updatedAt:'Today'});close()}}>Save project</button></div></div></div>}
