import { useEffect, useMemo, useState } from 'react';
import { Archive, Clock3, Filter, Pencil, Plus, Search, Sparkles, Trash2, X } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import { StatusPill } from '../components/StatusPill';
import type { Project, ProjectStatus } from '../types/domain';
import { deleteProject, upsertProject, useProjects } from '../lib/projectStore';
import { supabase } from '../lib/supabase';

type WalkthroughAssociation={id:string;room_name:string|null;captured_at:string;wall_count:number;door_count:number;window_count:number;archived_at:string|null;paintable_wall_sqft:number|null;average_wall_height_ft:number|null};
type TimeAssociation={id:string;clock_in:string;clock_out:string|null;status:string};

const blank=():Project=>({id:crypto.randomUUID(),name:'',address:'',clientName:'',status:'estimating',trade:'painting',progress:0,crewCount:0,updatedAt:'Today'});

export function Projects(){
 const projects=useProjects(); const [search,setSearch]=useState(''); const [editing,setEditing]=useState<Project|null>(null); const [details,setDetails]=useState<Project|null>(null); const [params,setParams]=useSearchParams();
 const filtered=projects.filter(p=>`${p.name} ${p.clientName} ${p.address}`.toLowerCase().includes(search.toLowerCase()));
 useEffect(()=>{const id=params.get('project'); if(!id)return; const match=projects.find(p=>p.id===id); if(match)setDetails(match)},[params,projects]);
 const closeDetails=()=>{setDetails(null); if(params.has('project')){const next=new URLSearchParams(params);next.delete('project');setParams(next,{replace:true})}};
 return <div className="page"><header className="page-header"><div><p className="eyebrow">Operations</p><h1>Projects</h1><p>One source of truth from lead through closeout.</p></div><button className="button primary" onClick={()=>setEditing(blank())}><Plus size={18}/>New project</button></header>
 <div className="toolbar"><label className="search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search projects, clients, addresses…"/></label><button className="button secondary"><Filter size={17}/>Filter</button></div>
 <div className="table-wrap"><table><thead><tr><th>Project</th><th>Status</th><th>Trade</th><th>Progress</th><th>Crew</th><th>Updated</th><th></th></tr></thead><tbody>{filtered.map(p=><tr key={p.id} className="project-table-row" onClick={()=>setDetails(p)}><td><strong>{p.name}</strong><span>{p.clientName}<br/>{p.address}</span></td><td><StatusPill status={p.status}/></td><td className="capitalize">{p.trade}</td><td><div className="progress"><i style={{width:`${p.progress}%`}}/></div><span>{p.progress}%</span></td><td>{p.crewCount}</td><td>{p.updatedAt}</td><td><div className="row-actions"><button aria-label="Edit project" onClick={e=>{e.stopPropagation();setEditing(p)}}><Pencil size={16}/></button><button aria-label="Delete project" onClick={e=>{e.stopPropagation();if(confirm(`Delete ${p.name}?`)) deleteProject(p.id)}}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>
 {editing&&<ProjectModal project={editing} close={()=>setEditing(null)}/>} {details&&<ProjectDetailsModal project={details} close={closeDetails} edit={()=>{closeDetails();setEditing(details)}}/>}</div>
}

function ProjectDetailsModal({project,close,edit}:{project:Project;close:()=>void;edit:()=>void}){
 const [walkthroughs,setWalkthroughs]=useState<WalkthroughAssociation[]>([]); const [timecards,setTimecards]=useState<TimeAssociation[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{let live=true; void (async()=>{if(!supabase){setLoading(false);return} const [walkRes,timeRes]=await Promise.all([
   supabase.from('walkthrough_scans').select('id,room_name,captured_at,wall_count,door_count,window_count,archived_at,paintable_wall_sqft,average_wall_height_ft').eq('project_id',project.id).order('captured_at',{ascending:false}),
   supabase.from('time_entries').select('id,clock_in,clock_out,status').eq('project_id',project.id).order('clock_in',{ascending:false})
 ]); if(!live)return; if(!walkRes.error)setWalkthroughs((walkRes.data??[]) as WalkthroughAssociation[]); if(!timeRes.error)setTimecards((timeRes.data??[]) as TimeAssociation[]); setLoading(false)})();return()=>{live=false}},[project.id]);
 const taggedRooms=walkthroughs.length; const archived=walkthroughs.filter(w=>w.archived_at).length; const measuredSqft=walkthroughs.reduce((n,w)=>n+(Number(w.paintable_wall_sqft)||0),0); const recordedHours=timecards.reduce((n,t)=>{if(!t.clock_out)return n;return n+Math.max(0,(new Date(t.clock_out).getTime()-new Date(t.clock_in).getTime())/3600000)},0);
 const localWalkthroughs=useMemo(()=>{try{const all=JSON.parse(localStorage.getItem('aurelium.walkthroughs.web.v1')||'[]') as Array<{projectId:string;room:string;createdAt:string;tags:number;notes:string}>;return all.filter(w=>w.projectId===project.id)}catch{return[]}},[project.id]);
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal-card project-detail-modal"><div className="modal-head"><div><p className="eyebrow">Project hub</p><h2>{project.name}</h2><p className="detail-subtitle">{project.clientName||'No client assigned'}{project.address?` · ${project.address}`:''}</p></div><button className="icon-button" onClick={close}><X/></button></div>
 <div className="detail-hero"><div><StatusPill status={project.status}/><strong>{project.progress}% complete</strong><span className="capitalize">{project.trade}</span></div><button className="button secondary" onClick={edit}><Pencil size={16}/>Edit project</button></div>
 <div className="detail-metrics"><div><small>Walkthrough rooms</small><strong>{taggedRooms||localWalkthroughs.length}</strong><span>{archived} archived</span></div><div><small>Measured walls</small><strong>{measuredSqft?`${Math.round(measuredSqft).toLocaleString()} sf`:'—'}</strong><span>RoomPlan paintable area</span></div><div><small>My recorded time</small><strong>{recordedHours.toFixed(1)} hr</strong><span>{timecards.length} timecards</span></div></div>
 <section className="detail-section"><div className="section-title"><div><p className="eyebrow">Associations</p><h3>Smart Walkthroughs</h3></div><a className="button ghost" href="#/estimator"><Sparkles size={16}/>Open Estimate</a></div>{loading?<p className="muted">Loading project associations…</p>:walkthroughs.length===0&&localWalkthroughs.length===0?<div className="compact-empty"><Archive/><strong>No walkthroughs yet</strong><span>Room scans, 3D models, measurements and evidence will appear here.</span></div>:<div className="detail-associations">{walkthroughs.map(w=><div key={w.id}><div><strong>{w.room_name||'Room walkthrough'}</strong><span>{new Date(w.captured_at).toLocaleString()}</span></div><div><span>{w.wall_count} walls · {w.door_count} doors · {w.window_count} windows</span>{w.paintable_wall_sqft!=null&&<span>{Math.round(Number(w.paintable_wall_sqft))} sf paintable walls</span>}</div>{w.archived_at&&<b>ARCHIVED</b>}</div>)}{walkthroughs.length===0&&localWalkthroughs.map(w=><div key={`${w.room}-${w.createdAt}`}><div><strong>{w.room}</strong><span>{w.createdAt}</span></div><div><span>{w.tags} tagged items · web/local record</span></div></div>)}</div>}</section>
 <section className="detail-section"><p className="eyebrow">Time</p><h3>My time on this project</h3><div className="detail-time"><Clock3/><div><strong>{recordedHours.toFixed(1)} hours recorded</strong><span>Employee view shows only the signed-in employee's allowed time records. Admin View provides organization-wide review.</span></div></div></section>
 </div></div>
}

function ProjectModal({project,close}:{project:Project;close:()=>void}){const [draft,setDraft]=useState(project); const set=(k:keyof Project,v:string|number)=>setDraft(d=>({...d,[k]:v})); return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal-card"><div className="modal-head"><div><p className="eyebrow">Job record</p><h2>{project.name?'Edit project':'New project'}</h2></div><button className="icon-button" onClick={close}><X/></button></div><div className="form-grid"><label>Project name<input value={draft.name} onChange={e=>set('name',e.target.value)}/></label><label>Client<input value={draft.clientName} onChange={e=>set('clientName',e.target.value)}/></label><label className="wide">Address / location<input value={draft.address} onChange={e=>set('address',e.target.value)}/></label><label>Status<select value={draft.status} onChange={e=>set('status',e.target.value as ProjectStatus)}>{['lead','estimating','scheduled','active','paused','complete','archived'].map(x=><option key={x}>{x}</option>)}</select></label><label>Trade<select value={draft.trade} onChange={e=>set('trade',e.target.value as Project['trade'])}>{['painting','general','drywall','flooring','roofing','other'].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="modal-actions"><button className="button secondary" onClick={close}>Cancel</button><button className="button primary" disabled={!draft.name.trim()} onClick={()=>{upsertProject({...draft,updatedAt:'Today'});close()}}>Save project</button></div></div></div>}
