import { useEffect, useMemo, useState } from 'react';
import { Clock3, MapPin, CheckCircle2, ShieldCheck, LogOut, Play, Square, CalendarDays, BriefcaseBusiness, Tag, ChevronRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import { useAuth } from '../auth/AuthGate';

type ProjectRow={id:string;name:string};
type TimeRow={id:string;project_id:string;clock_in:string;clock_out:string|null;cost_code:string|null;notes:string|null;status:string;submitted_at:string|null};
type Coords={latitude:number;longitude:number;accuracy:number};
const commonCodes=['Painting','Prep','Punch','Travel','Shop','Supervision'];

export function Team(){
 const {user,membership,isAdmin,signOut}=useAuth();
 const [projects,setProjects]=useState<ProjectRow[]>([]);const [entries,setEntries]=useState<TimeRow[]>([]);const [project,setProject]=useState('');const [costCode,setCostCode]=useState('Painting');const [notes,setNotes]=useState('');const [coords,setCoords]=useState<Coords|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [showClockIn,setShowClockIn]=useState(false);const [now,setNow]=useState(Date.now());
 const active=useMemo(()=>entries.find(e=>!e.clock_out),[entries]);
 const projectMap=useMemo(()=>Object.fromEntries(projects.map(p=>[p.id,p.name])),[projects]);
 useEffect(()=>{if(!active)return;const id=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(id)},[active?.id]);
 const refresh=async()=>{if(!supabase||!membership||!user)return;const [{data:p,error:pe},{data:t,error:te}]=await Promise.all([supabase.from('projects').select('id,name').eq('organization_id',membership.organization_id).order('updated_at',{ascending:false}),supabase.from('time_entries').select('id,project_id,clock_in,clock_out,cost_code,notes,status,submitted_at').eq('organization_id',membership.organization_id).eq('user_id',user.id).order('clock_in',{ascending:false}).limit(60)]);if(pe||te){setError('Your timesheet could not be loaded. Reference: AF-TIME-101');return}setProjects((p??[]) as ProjectRow[]);setEntries((t??[]) as TimeRow[]);if(!project&&p?.[0])setProject(p[0].id)};
 useEffect(()=>{void refresh()},[membership?.organization_id,user?.id]);
 const locate=()=>new Promise<Coords>((resolve,reject)=>navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy}),reject,{enableHighAccuracy:true,timeout:12000,maximumAge:15000}));
 const clockIn=async()=>{if(!supabase||!membership||!user||!project)return;setBusy(true);setError('');try{let c:Coords|null=null;try{c=await locate();setCoords(c)}catch{/* allow server policy to decide if location is required */}const {error}=await supabase.from('time_entries').insert({organization_id:membership.organization_id,project_id:project,user_id:user.id,clock_in:new Date().toISOString(),cost_code:costCode||null,notes:notes||null,clock_in_latitude:c?.latitude??null,clock_in_longitude:c?.longitude??null,clock_in_accuracy_m:c?.accuracy??null});if(error)throw error;setShowClockIn(false);setNotes('');await refresh()}catch{setError('Clock in could not be completed. Reference: AF-TIME-102')}finally{setBusy(false)}};
 const clockOut=async()=>{if(!supabase||!active)return;setBusy(true);setError('');try{let c:Coords|null=null;try{c=await locate();setCoords(c)}catch{}const {error}=await supabase.from('time_entries').update({clock_out:new Date().toISOString(),clock_out_latitude:c?.latitude??null,clock_out_longitude:c?.longitude??null,clock_out_accuracy_m:c?.accuracy??null}).eq('id',active.id);if(error)throw error;await refresh()}catch{setError('Clock out could not be completed. Reference: AF-TIME-103')}finally{setBusy(false)}};
 const submit=async(id:string)=>{if(!supabase||!confirm('Confirm and submit this timecard? Changes after submission require admin approval.'))return;const {error}=await supabase.rpc('submit_time_entry',{entry_id:id});if(error)setError('Timecard could not be submitted. Reference: AF-TIME-104');else await refresh()};
 const weekStart=useMemo(()=>{const d=new Date();const day=d.getDay();d.setHours(0,0,0,0);d.setDate(d.getDate()-day);return d},[]);
 const weekly=entries.filter(e=>new Date(e.clock_in)>=weekStart);const weeklyHours=weekly.reduce((sum,e)=>sum+(e.clock_out?Math.max(0,new Date(e.clock_out).getTime()-new Date(e.clock_in).getTime())/36e5:0),0);

 return <div className="page time-page"><header className="page-header"><div><p className="eyebrow">Employee workspace</p><h1>My Time</h1><p>Clock in to the job, track your current shift and submit a clean weekly timesheet.</p></div><div className="account-actions">{isAdmin&&<Link className="button secondary" to="/admin"><ShieldCheck size={17}/>Admin View</Link>}<button className="button secondary" onClick={()=>void signOut()}><LogOut size={17}/>Sign Out</button></div></header>
 <div className="time-dashboard">
  <section className={`time-hero ${active?'active':''}`}><div className="time-hero-head"><div><p className="eyebrow">{active?'On the clock':'Ready to work'}</p><h2>{active?'Current shift':'Clock in'}</h2></div><Clock3 size={26}/></div>
   {active?<><div className="live-time">{formatElapsed(now-new Date(active.clock_in).getTime())}</div><strong className="live-project">{projectMap[active.project_id]||'Project'}</strong><div className="time-meta"><span><Tag size={15}/>{active.cost_code||'No cost code'}</span><span><MapPin size={15}/>GPS verification enabled</span></div><button className="clock-button clock-out" disabled={busy} onClick={clockOut}><Square size={18} fill="currentColor"/>{busy?'Clocking out…':'Clock Out'}</button></>:<><div className="ready-time">{new Date(now).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</div><span className="ready-date">{new Date(now).toLocaleDateString([],{weekday:'long',month:'long',day:'numeric'})}</span><button className="clock-button clock-in" disabled={busy||projects.length===0} onClick={()=>setShowClockIn(true)}><Play size={18} fill="currentColor"/>Clock In</button><small>{projects.length?'Choose a project and cost code before starting.':'Add or sync a project before clocking in.'}</small></>}
  </section>
  <section className="time-week panel"><div className="section-title"><div><p className="eyebrow">This week</p><h2>Timesheet</h2></div><strong className="week-total">{weeklyHours.toFixed(2)} h</strong></div><div className="week-metrics"><div><strong>{weeklyHours.toFixed(2)}</strong><span>Regular hours</span></div><div><strong>{weekly.length}</strong><span>Shifts</span></div><div><strong>{weekly.filter(e=>e.status==='submitted'||e.status==='approved').length}</strong><span>Submitted</span></div></div></section>
 </div>
 <section className="panel timecards-panel"><div className="section-title"><div><p className="eyebrow">History</p><h2>Recent timecards</h2></div><span className="muted">{entries.length} entries</span></div>{entries.length===0?<div className="compact-empty"><Clock3/><strong>No time yet</strong><span>Completed shifts will appear here.</span></div>:<div className="timesheet-list">{entries.slice(0,30).map(e=><div className="timesheet-row" key={e.id}><div className="timesheet-date"><b>{new Date(e.clock_in).getDate()}</b><span>{new Date(e.clock_in).toLocaleDateString([],{month:'short'})}</span></div><div className="timesheet-main"><strong>{projectMap[e.project_id]||'Project'}</strong><span>{timeRange(e)} · {e.cost_code||'No cost code'}</span>{e.notes&&<small>{e.notes}</small>}</div><div className="timesheet-value"><strong>{entryHours(e)}</strong><span className={`time-status status-${e.status}`}>{e.status}</span></div>{(e.status==='draft'||e.status==='rejected')&&e.clock_out&&<button className="time-submit" onClick={()=>submit(e.id)}><CheckCircle2 size={15}/>{e.status==='rejected'?'Resubmit':'Submit'}</button>}</div>)}</div>}</section>
 {coords&&<p className="time-location-note"><MapPin size={14}/>Last location accuracy ±{Math.round(coords.accuracy)} m</p>}
 {showClockIn&&<div className="modal-backdrop"><div className="modal-card clockin-modal"><div className="modal-head"><div><p className="eyebrow">Start shift</p><h2>Clock in</h2></div><button className="icon-button" onClick={()=>setShowClockIn(false)}>×</button></div><div className="clockin-form"><label>Project<select value={project} onChange={e=>setProject(e.target.value)}><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Cost code<div className="cost-code-chips">{commonCodes.map(c=><button type="button" key={c} className={costCode===c?'selected':''} onClick={()=>setCostCode(c)}>{c}</button>)}</div><input value={costCode} onChange={e=>setCostCode(e.target.value)}/></label><label>Shift notes<textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Optional notes"/></label><div className="clockin-location"><MapPin size={16}/><span>Aurelium will request current jobsite location when you clock in.</span></div><button className="clock-button clock-in" disabled={busy||!project} onClick={clockIn}><Play size={17} fill="currentColor"/>{busy?'Starting…':'Clock In'}</button></div></div></div>}
 {error&&<div className="error-banner">{error}</div>}</div>
}

function formatElapsed(ms:number){const s=Math.max(0,Math.floor(ms/1000));return [Math.floor(s/3600),Math.floor((s%3600)/60),s%60].map(v=>String(v).padStart(2,'0')).join(':')}
function entryHours(e:TimeRow){if(!e.clock_out)return'Active';return `${Math.max(0,(new Date(e.clock_out).getTime()-new Date(e.clock_in).getTime())/36e5).toFixed(2)} h`}
function timeRange(e:TimeRow){const start=new Date(e.clock_in).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});const end=e.clock_out?new Date(e.clock_out).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'Now';return `${start} – ${end}`}
