import { useEffect, useMemo, useState } from 'react';
import { Clock3, MapPin, Share2, UserPlus, CheckCircle2 } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { useAuth } from '../auth/AuthGate';

type ProjectRow={id:string;name:string};
type TimeRow={id:string;project_id:string;clock_in:string;clock_out:string|null;cost_code:string|null;notes:string|null;status:string;submitted_at:string|null};
type Coords={latitude:number;longitude:number;accuracy:number};

export function Team(){
 const {user,membership,isAdmin}=useAuth(); const [projects,setProjects]=useState<ProjectRow[]>([]);const [entries,setEntries]=useState<TimeRow[]>([]);const [project,setProject]=useState('');const [costCode,setCostCode]=useState('Painting');const [notes,setNotes]=useState('');const [coords,setCoords]=useState<Coords|null>(null);const [busy,setBusy]=useState(false);const [invite,setInvite]=useState('');const [inviteEmail,setInviteEmail]=useState('');const [inviteRole,setInviteRole]=useState('crew');const [error,setError]=useState('');
 const active=useMemo(()=>entries.find(e=>!e.clock_out),[entries]);
 const refresh=async()=>{if(!supabase||!membership||!user)return;const [{data:p},{data:t}]=await Promise.all([supabase.from('projects').select('id,name').eq('organization_id',membership.organization_id).order('updated_at',{ascending:false}),supabase.from('time_entries').select('id,project_id,clock_in,clock_out,cost_code,notes,status,submitted_at').eq('organization_id',membership.organization_id).eq('user_id',user.id).order('clock_in',{ascending:false}).limit(30)]);setProjects((p??[]) as ProjectRow[]);setEntries((t??[]) as TimeRow[]);if(!project&&p?.[0])setProject(p[0].id)};
 useEffect(()=>{void refresh()},[membership?.organization_id,user?.id]);
 const locate=()=>new Promise<Coords>((resolve,reject)=>navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy}),reject,{enableHighAccuracy:true,timeout:12000,maximumAge:15000}));
 const clockIn=async()=>{if(!supabase||!membership||!user||!project)return;setBusy(true);setError('');try{const c=await locate();setCoords(c);const {error}=await supabase.from('time_entries').insert({organization_id:membership.organization_id,project_id:project,user_id:user.id,clock_in:new Date().toISOString(),cost_code:costCode||null,notes:notes||null,clock_in_latitude:c.latitude,clock_in_longitude:c.longitude,clock_in_accuracy_m:c.accuracy});if(error)throw error;await refresh()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 const clockOut=async()=>{if(!supabase||!active)return;setBusy(true);try{const c=await locate();setCoords(c);const {error}=await supabase.from('time_entries').update({clock_out:new Date().toISOString(),clock_out_latitude:c.latitude,clock_out_longitude:c.longitude,clock_out_accuracy_m:c.accuracy}).eq('id',active.id);if(error)throw error;await refresh()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 const submit=async(id:string)=>{if(!supabase||!confirm('Confirm and submit this timecard? Changes after submission require admin approval.'))return;const {error}=await supabase.rpc('submit_time_entry',{entry_id:id});if(error)setError(error.message);else await refresh()};
 const createInvite=async()=>{if(!supabase)return;setError('');const {data,error}=await supabase.rpc('create_organization_invite',{invite_email:inviteEmail.trim()||null,invite_role:inviteRole});if(error){setError(error.message);return}const token=(data as {token:string}[]|null)?.[0]?.token;if(token)setInvite(`${location.origin}${location.pathname}#/join?invite=${token}`)};
 return <div className="page"><header className="page-header"><div><p className="eyebrow">People & time</p><h1>Team</h1><p>GPS-backed timecards, organization access, and approvals.</p></div></header>
 <div className="panel"><div className="panel-title"><div><p className="eyebrow">My shift</p><h2>{active?'Clocked in':'Ready to clock in'}</h2></div><Clock3/></div>{active?<div className="time-clock-active"><strong>Started {new Date(active.clock_in).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</strong><p className="muted"><MapPin size={15}/> GPS verifies field time while location is available.</p><button className="button primary danger" disabled={busy} onClick={clockOut}>Clock out</button></div>:<div className="form-grid"><label>Project<select value={project} onChange={e=>setProject(e.target.value)}><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Cost code<input value={costCode} onChange={e=>setCostCode(e.target.value)}/></label><label className="wide">Shift notes<input value={notes} onChange={e=>setNotes(e.target.value)}/></label><div className="wide"><button className="button primary" disabled={busy||!project} onClick={clockIn}><MapPin size={17}/>Clock in with GPS</button></div></div>}{coords&&<p className="muted">Last location accuracy: ±{Math.round(coords.accuracy)} m</p>}</div>
 <div className="panel"><h2>My timecards</h2><div className="time-list">{entries.filter(e=>e.clock_out).map(e=><div className="time-row" key={e.id}><div><strong>{new Date(e.clock_in).toLocaleDateString()} · {new Date(e.clock_in).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</strong><span>{e.clock_out?` → ${new Date(e.clock_out).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}`:''} · {e.status}</span></div>{e.status==='draft'&&<button className="button secondary" onClick={()=>submit(e.id)}><CheckCircle2 size={16}/>Review & submit</button>}</div>)}</div></div>
 {isAdmin&&<div className="panel"><div className="panel-title"><div><p className="eyebrow">Organization</p><h2>Invite employees</h2></div><UserPlus/></div><div className="form-grid"><label>Email (optional)<input type="email" value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)}/></label><label>Role<select value={inviteRole} onChange={e=>setInviteRole(e.target.value)}>{['crew','foreman','estimator','pm','office','admin'].map(r=><option key={r} value={r}>{r}</option>)}</select></label><div className="wide"><button className="button primary" onClick={createInvite}>Generate join link</button></div></div>{invite&&<div className="invite-link"><code>{invite}</code><button className="button secondary" onClick={()=>navigator.share?navigator.share({url:invite,title:'Join our Aurelium Field organization'}):navigator.clipboard.writeText(invite)}><Share2 size={16}/>Share</button></div>}</div>}
 {error&&<div className="error-banner">{error}</div>}</div>
}
