import { CalendarDays, CheckCircle2, ChevronRight, Filter, Plus } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useAppData } from '../contexts/AppDataContext'
import { addDaysISO, todayISO } from '../lib/time'
import type { ItemType, LifeItem } from '../types'
import { ItemCard } from '../components/ItemCard'
import { Modal } from '../components/Modal'
const filters:Array<'all'|ItemType>=['all','task','errand','shopping','call','chore','reminder','idea']
function group(items:LifeItem[]){const t=todayISO(),week=addDaysISO(7);return {today:items.filter(i=>i.due_date&&i.due_date<=t),week:items.filter(i=>i.due_date&&i.due_date>t&&i.due_date<=week),someday:items.filter(i=>!i.due_date||i.due_date>week)}}
export default function LaterPage(){
  const {items,createEvent,spaces}=useAppData(); const [filter,setFilter]=useState<typeof filters[number]>('all'); const [eventOpen,setEventOpen]=useState(false)
  const [eventTitle,setEventTitle]=useState('');const [eventDate,setEventDate]=useState(todayISO());const [eventStart,setEventStart]=useState('18:00');const [eventEnd,setEventEnd]=useState('');const [eventLocation,setEventLocation]=useState('');const [eventSpace,setEventSpace]=useState('')
  const open=useMemo(()=>items.filter(i=>i.status==='open'&&(filter==='all'||i.type===filter)),[items,filter]);const g=group(open)
  async function addEvent(){if(!eventTitle.trim())return;await createEvent({title:eventTitle.trim(),event_date:eventDate,start_time:eventStart,end_time:eventEnd||null,location:eventLocation||null,notes:null,space_id:eventSpace||null});setEventTitle('');setEventLocation('');setEventEnd('');setEventOpen(false)}
  return <div className="page"><header className="page-header"><div><span className="eyebrow">LATER</span><h1>Everything waiting for you.</h1><p>Organized loosely, so you don’t have to babysit a system.</p></div><div className="header-actions"><div className="header-stat"><strong>{open.length}</strong><span>open</span></div><button className="secondary-button" onClick={()=>setEventOpen(true)}><CalendarDays size={17}/>Add event</button></div></header><div className="filter-row"><Filter size={16}/>{filters.map(f=><button key={f} className={`chip ${filter===f?'active':''}`} onClick={()=>setFilter(f)}>{f}</button>)}</div>{open.length===0?<div className="large-empty"><CheckCircle2/><h2>Nothing waiting for you.</h2><p>Enjoy it.</p></div>:<div className="later-columns">{([['Today',g.today],['This week',g.week],['Someday',g.someday]] as [string,LifeItem[]][]).map(([name,list])=><section className="later-section" key={name}><div className="section-heading inline"><h2>{name}</h2><span>{list.length}</span></div>{list.length?list.map(i=><ItemCard key={i.id} item={i}/>):<div className="empty-row">Nothing here <ChevronRight size={15}/></div>}</section>)}</div>}<div className="later-note"><CalendarDays size={18}/><span>Recurring items only appear here when they become relevant.</span></div><Modal open={eventOpen} onClose={()=>setEventOpen(false)} title="Add event"><div className="form-stack"><label>Title<input value={eventTitle} onChange={e=>setEventTitle(e.target.value)} placeholder="Dinner, appointment, pickup…" autoFocus/></label><div className="two-col"><label>Date<input type="date" value={eventDate} onChange={e=>setEventDate(e.target.value)}/></label><label>Start<input type="time" value={eventStart} onChange={e=>setEventStart(e.target.value)}/></label></div><div className="two-col"><label>End (optional)<input type="time" value={eventEnd} onChange={e=>setEventEnd(e.target.value)}/></label><label>Space<select value={eventSpace} onChange={e=>setEventSpace(e.target.value)}><option value="">Personal</option>{spaces.filter(s=>!s.name.toLowerCase().includes('personal')).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div><label>Location<input value={eventLocation} onChange={e=>setEventLocation(e.target.value)} placeholder="Optional"/></label><button className="primary-button" onClick={addEvent} disabled={!eventTitle.trim()}><Plus size={17}/>Add event</button></div></Modal></div>}
