import { useMemo, useRef, useState } from 'react'
import { CalendarDays, Clock3, Download, MapPin, Plus, Upload } from 'lucide-react'
import { useAppData } from '../contexts/AppDataContext'
import { useOrganizer } from '../contexts/OrganizerContext'
import { agendaForDate, addDays, formatClock, formatFriendlyDate, isoToday } from '../lib/organizer'
import { inspectFile } from '../lib/smartIntake'

export default function PlannerPage(){
 const {items,events,createEvent,importCalendarEvents}=useAppData(); const {projects,reminders,createReminder}=useOrganizer(); const [selected,setSelected]=useState(isoToday()); const [creating,setCreating]=useState(false)
 const [title,setTitle]=useState(''),[time,setTime]=useState('09:00'),[end,setEnd]=useState(''),[location,setLocation]=useState(''),[projectId,setProjectId]=useState(''),[remind,setRemind]=useState('30')
 const [importing,setImporting]=useState(false),[importMessage,setImportMessage]=useState(''); const fileRef=useRef<HTMLInputElement|null>(null)
 const days=useMemo(()=>Array.from({length:14},(_,i)=>addDays(i)),[]); const agenda=useMemo(()=>agendaForDate(selected,items,events),[selected,items,events])
 async function save(){if(!title.trim())return;const created=await createEvent({title:title.trim(),event_date:selected,start_time:time,end_time:end||null,location:location||null,notes:null,attendees:[],recurrence_rule:null,project_id:projectId||null,provider:'internal',external_id:null}); if(Number(remind)>=0){const when=new Date(`${selected}T${time}:00`);when.setMinutes(when.getMinutes()-Number(remind));await createReminder({title,body:location?`At ${location}`:null,remind_at:when.toISOString(),event_id:created.id})} setTitle('');setLocation('');setEnd('');setProjectId('');setCreating(false)}
 async function importFile(file:File){setImporting(true);setImportMessage('');try{const inspected=await inspectFile(file);if(!inspected.events.length)throw new Error('No calendar events were found. Try an .ics export or an Outlook-style calendar CSV.');const result=await importCalendarEvents(inspected.events,file.name);setImportMessage(`Imported ${result.imported} event${result.imported===1?'':'s'}${result.skipped?` · ${result.skipped} duplicate${result.skipped===1?'':'s'} skipped`:''}.`)}catch(e){setImportMessage(e instanceof Error?e.message:'Calendar import failed.')}finally{setImporting(false);if(fileRef.current)fileRef.current.value=''}}
 return <div className="page organizer-page"><header className="page-header"><div><span className="eyebrow">PLANNER</span><h1>Your time and your tasks, together.</h1><p>Appointments, deadlines and reminders share one timeline so the day actually makes sense.</p></div><div className="header-actions"><input ref={fileRef} className="sr-only" type="file" accept=".ics,.csv,text/calendar,text/csv" onChange={e=>{const file=e.target.files?.[0];if(file)void importFile(file)}}/><button className="secondary-button" onClick={()=>fileRef.current?.click()} disabled={importing}><Upload size={17}/>{importing?'Importing…':'Import calendar'}</button><button className="primary-button" onClick={()=>setCreating(v=>!v)}><Plus size={17}/>Appointment</button></div></header>
 <div className="calendar-import-note"><Download size={16}/><div><strong>Calendar import is live now.</strong><span>Import an <code>.ics</code> file from Outlook, Google Calendar, Apple Calendar, or another calendar app. Common Outlook/calendar <code>.csv</code> exports are supported too. Provider IDs are preserved when available so repeated imports can be de-duplicated.</span>{importMessage&&<b>{importMessage}</b>}</div></div>
 <div className="date-strip">{days.map(d=><button key={d} className={selected===d?'active':''} onClick={()=>setSelected(d)}><span>{new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'short'})}</span><strong>{new Date(d+'T12:00:00').getDate()}</strong></button>)}</div>
 {creating&&<section className="panel-card planner-create"><div className="form-stack"><label>Appointment<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="Dentist, meeting, dinner…"/></label><div className="two-col"><label>Starts<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><label>Ends<input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><label>Location<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Optional"/></label><div className="two-col"><label>Project<select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">None</option>{projects.filter(p=>p.status==='active').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Remind me<select value={remind} onChange={e=>setRemind(e.target.value)}><option value="0">At start</option><option value="10">10 min before</option><option value="30">30 min before</option><option value="60">1 hour before</option><option value="1440">1 day before</option></select></label></div><div className="row-actions"><button className="secondary-button" onClick={()=>setCreating(false)}>Cancel</button><button className="primary-button" disabled={!title.trim()} onClick={save}>Save appointment</button></div></div></section>}
 <div className="planner-grid"><section className="panel-card agenda-panel"><div className="section-heading"><div><span className="eyebrow">AGENDA</span><h2>{formatFriendlyDate(selected)}</h2></div></div><div className="timeline">{agenda.map(row=><article key={`${row.kind}-${row.id}`} className={`timeline-row ${row.kind}`}><time>{formatClock(row.time)}</time><div className="timeline-dot"/><div><strong>{row.title}</strong>{row.kind==='event'&&row.event.location&&<span><MapPin size={13}/>{row.event.location}</span>}{row.kind==='event'&&row.event.provider&&row.event.provider!=='internal'&&<span>{row.event.provider}</span>}{row.kind==='task'&&row.item.estimated_minutes&&<span><Clock3 size={13}/>{row.item.estimated_minutes} min task</span>}</div></article>)}</div>{!agenda.length&&<div className="empty-state"><CalendarDays/><strong>Open day.</strong><span>No appointments or due tasks yet.</span></div>}</section>
 <aside className="panel-card reminders-panel"><div className="section-heading"><div><span className="eyebrow">REMINDERS</span><h2>Coming up</h2></div><span className="count-pill">{reminders.length}</span></div><div className="reminder-list">{reminders.slice(0,8).map(r=><div key={r.id}><span className="reminder-time">{new Date(r.remind_at).toLocaleString(undefined,{weekday:'short',hour:'numeric',minute:'2-digit'})}</span><strong>{r.title}</strong></div>)}</div>{!reminders.length&&<p className="muted-copy">Add reminders to appointments from the planner. The iOS wrapper schedules native local notifications.</p>}</aside></div></div>
}
