import { CalendarDays, Clock3, Download, Edit3, MapPin, Phone, Plus, Trash2, Upload, UserRound } from 'lucide-react'
import { useMemo, useRef, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { useAppData } from '../contexts/AppDataContext'
import { useAuth } from '../contexts/AuthContext'
import { useOrganizer } from '../contexts/OrganizerContext'
import { agendaForDate, addDays, formatClock, formatFriendlyDate, isoToday } from '../lib/organizer'
import { inspectFile } from '../lib/smartIntake'
import { contactPrimaryPhone, dialHref } from '../lib/contacts'
import { spaceCategoryAccess } from '../lib/spacePermissions'
import type { EventItem } from '../types'

export default function PlannerPage(){
 const {userId}=useAuth(); const {items,events,spaces,members,contacts,createEvent,updateEvent,deleteEvent,importCalendarEvents}=useAppData(); const {projects,reminders,createReminder}=useOrganizer(); const [params]=useSearchParams(); const spaceId=params.get('space')||''; const space=spaces.find(candidate=>candidate.id===spaceId)
 const member=space?members.find(m=>m.space_id===space.id&&m.user_id===userId):undefined; const access=spaceCategoryAccess(space,member,'calendar'); const canEdit=!spaceId||access.canEdit
 const [selected,setSelected]=useState(isoToday()); const [creating,setCreating]=useState(false); const [editingEvent,setEditingEvent]=useState<EventItem|null>(null)
 const [title,setTitle]=useState(''),[time,setTime]=useState('09:00'),[end,setEnd]=useState(''),[location,setLocation]=useState(''),[projectId,setProjectId]=useState(''),[contactId,setContactId]=useState(''),[remind,setRemind]=useState('30')
 const [importing,setImporting]=useState(false),[importMessage,setImportMessage]=useState(''); const fileRef=useRef<HTMLInputElement|null>(null)
 const days=useMemo(()=>Array.from({length:14},(_,i)=>addDays(i)),[])
 const scopedItems=useMemo(()=>spaceId?items.filter(item=>item.space_id===spaceId):items,[items,spaceId]); const scopedEvents=useMemo(()=>spaceId?events.filter(event=>event.space_id===spaceId):events,[events,spaceId]); const agenda=useMemo(()=>agendaForDate(selected,scopedItems,scopedEvents),[selected,scopedItems,scopedEvents])
 function eventEditable(event:EventItem){if(!event.space_id)return true;const eventSpace=spaces.find(candidate=>candidate.id===event.space_id);const eventMember=eventSpace?members.find(candidate=>candidate.space_id===eventSpace.id&&candidate.user_id===userId):undefined;return spaceCategoryAccess(eventSpace,eventMember,'calendar').canEdit}
 const projectOptions=projects.filter(project=>project.status==='active'&&(!spaceId||project.space_id===spaceId))
 function resetForm(){setTitle('');setTime('09:00');setEnd('');setLocation('');setProjectId('');setContactId('');setRemind('30');setEditingEvent(null)}
 function startCreate(){if(!canEdit)return;resetForm();setCreating(true)}
 function startEdit(event:EventItem){if(!eventEditable(event))return;setEditingEvent(event);setSelected(event.event_date);setTitle(event.title);setTime(event.start_time?.slice(0,5)||'09:00');setEnd(event.end_time?.slice(0,5)||'');setLocation(event.location||'');setProjectId(event.project_id||'');setContactId(event.contact_id||'');setCreating(true)}
 async function save(){if(!title.trim()||!canEdit)return;if(editingEvent){if(!eventEditable(editingEvent))return;await updateEvent(editingEvent.id,{title:title.trim(),event_date:selected,start_time:time,end_time:end||null,location:location||null,project_id:projectId||null,contact_id:contactId||null});setCreating(false);resetForm();return}const created=await createEvent({title:title.trim(),event_date:selected,start_time:time,end_time:end||null,location:location||null,notes:null,attendees:[],recurrence_rule:null,project_id:projectId||null,contact_id:contactId||null,space_id:spaceId||null,provider:'internal',external_id:null}); if(Number(remind)>=0){const when=new Date(`${selected}T${time}:00`);when.setMinutes(when.getMinutes()-Number(remind));await createReminder({title,body:location?`At ${location}`:null,remind_at:when.toISOString(),event_id:created.id})} setCreating(false);resetForm()}
 async function removeEvent(){if(!editingEvent||!eventEditable(editingEvent))return;await deleteEvent(editingEvent.id);setCreating(false);resetForm()}
 async function importFile(file:File){if(!canEdit)return;setImporting(true);setImportMessage('');try{const inspected=await inspectFile(file);if(!inspected.events.length)throw new Error('No calendar events were found. Try an .ics export or an Outlook-style calendar CSV.');const eventsForSpace=inspected.events.map(event=>({...event,space_id:spaceId||null}));const result=await importCalendarEvents(eventsForSpace,file.name);setImportMessage(`Imported ${result.imported} event${result.imported===1?'':'s'}${result.skipped?` · ${result.skipped} duplicate${result.skipped===1?'':'s'} skipped`:''}.`)}catch(e){setImportMessage(e instanceof Error?e.message:'Calendar import failed.')}finally{setImporting(false);if(fileRef.current)fileRef.current.value=''}}
 return <div className="page organizer-page"><header className="page-header"><div><span className="eyebrow">PLANNER{space?` · ${space.name.toUpperCase()}`:''}</span><h1>Your time and your tasks, together.</h1><p>{space?`Appointments and deadlines shared inside ${space.name}.`:'Appointments, deadlines and reminders share one timeline so the day actually makes sense.'}</p></div><div className="header-actions"><input ref={fileRef} className="sr-only" type="file" accept=".ics,.csv,text/calendar,text/csv" onChange={e=>{const file=e.target.files?.[0];if(file)void importFile(file)}}/><button className="secondary-button" onClick={()=>fileRef.current?.click()} disabled={importing||!canEdit}><Upload size={17}/>{importing?'Importing…':'Import calendar'}</button><button className="primary-button" onClick={startCreate} disabled={!canEdit}><Plus size={17}/>Appointment</button></div></header>
 {spaceId&&!canEdit&&<div className="permission-note prominent">You have view-only access to Calendar in this Space.</div>}
 <div className="calendar-import-note"><Download size={16}/><div><strong>Calendar import is live now.</strong><span>Import an <code>.ics</code> file from Outlook, Google Calendar, Apple Calendar, or another calendar app. Common Outlook/calendar <code>.csv</code> exports are supported too.</span>{importMessage&&<b>{importMessage}</b>}</div></div>
 <div className="date-strip">{days.map(d=><button key={d} className={selected===d?'active':''} onClick={()=>setSelected(d)}><span>{new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'short'})}</span><strong>{new Date(d+'T12:00:00').getDate()}</strong></button>)}</div>
 {creating&&<section className="panel-card planner-create"><div className="form-stack"><div className="section-heading inline"><div><span className="eyebrow">{editingEvent?'EDIT APPOINTMENT':'NEW APPOINTMENT'}</span><h2>{editingEvent?'Change the details':'Add something to the schedule'}</h2></div>{editingEvent&&<button className="text-button danger-text" onClick={removeEvent}><Trash2 size={15}/>Delete</button>}</div><label>Appointment<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="Dentist, meeting, dinner…"/></label><div className="two-col"><label>Starts<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><label>Ends<input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><label>Location<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Optional"/></label><div className="two-col"><label>Project<select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">None</option>{projectOptions.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Contact<select value={contactId} onChange={e=>setContactId(e.target.value)}><option value="">None</option>{contacts.map(contact=><option key={contact.id} value={contact.id}>{contact.display_name}</option>)}</select></label></div>{!editingEvent&&<label>Remind me<select value={remind} onChange={e=>setRemind(e.target.value)}><option value="0">At start</option><option value="10">10 min before</option><option value="30">30 min before</option><option value="60">1 hour before</option><option value="1440">1 day before</option></select></label>}<div className="row-actions"><button className="secondary-button" onClick={()=>{setCreating(false);resetForm()}}>Cancel</button><button className="primary-button" disabled={!title.trim()} onClick={save}>{editingEvent?'Save changes':'Save appointment'}</button></div></div></section>}
 <div className="planner-grid"><section className="panel-card agenda-panel"><div className="section-heading"><div><span className="eyebrow">AGENDA</span><h2>{formatFriendlyDate(selected)}</h2></div></div><div className="timeline">{agenda.map(row=>{const linkedContact=contacts.find(contact=>contact.id===(row.kind==='event'?row.event.contact_id:row.item.contact_id));const phone=contactPrimaryPhone(linkedContact);return <article key={`${row.kind}-${row.id}`} className={`timeline-row ${row.kind}`}><time>{row.kind==='task'&&!row.item.due_time?'Anytime':formatClock(row.time)}</time><div className="timeline-dot"/><div className="timeline-content"><div className="timeline-title-actions"><strong>{row.title}</strong>{row.kind==='event'&&eventEditable(row.event)&&<button className="icon-button subtle" onClick={()=>startEdit(row.event)} aria-label={`Edit ${row.title}`}><Edit3 size={14}/></button>}</div>{row.kind==='event'&&row.event.location&&<span><MapPin size={13}/>{row.event.location}</span>}{linkedContact&&<span><UserRound size={13}/>{linkedContact.display_name}</span>}{row.kind==='event'&&row.event.provider&&row.event.provider!=='internal'&&<span>{row.event.provider}</span>}{row.kind==='task'&&row.item.estimated_minutes&&<span><Clock3 size={13}/>{row.item.estimated_minutes} min task</span>}{phone&&<a className="timeline-dial" href={dialHref(phone)}><Phone size={13}/>Dial</a>}</div></article>})}</div>{!agenda.length&&<div className="empty-state"><CalendarDays/><strong>Open day.</strong><span>No appointments or due tasks yet.</span></div>}</section>
 <aside className="panel-card reminders-panel"><div className="section-heading"><div><span className="eyebrow">REMINDERS</span><h2>Coming up</h2></div><span className="count-pill">{reminders.length}</span></div><div className="reminder-list">{reminders.slice(0,8).map(r=><div key={r.id}><span className="reminder-time">{new Date(r.remind_at).toLocaleString(undefined,{weekday:'short',hour:'numeric',minute:'2-digit'})}</span><strong>{r.title}</strong></div>)}</div>{!reminders.length&&<p className="muted-copy">Add reminders to appointments from the planner. The iOS wrapper schedules native local notifications.</p>}</aside></div></div>
}
