import { Archive, CalendarDays, FolderKanban, Lock, Plus, Target } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { useAppData } from '../contexts/AppDataContext'
import { useAuth } from '../contexts/AuthContext'
import { useOrganizer } from '../contexts/OrganizerContext'
import { projectProgress } from '../lib/organizer'
import { spaceCategoryAccess } from '../lib/spacePermissions'

export default function ProjectsPage(){
 const {userId}=useAuth(); const {items,spaces,members}=useAppData(); const {projects,createProject,archiveProject,expansionAvailable}=useOrganizer(); const nav=useNavigate(); const [params]=useSearchParams(); const spaceId=params.get('space')||''; const space=spaces.find(s=>s.id===spaceId)
 const member=space?members.find(m=>m.space_id===space.id&&m.user_id===userId):undefined; const access=spaceCategoryAccess(space,member,'projects'); const canEdit=!spaceId||access.canEdit
 function projectEditable(project:{space_id?:string|null}){if(!project.space_id)return true;const projectSpace=spaces.find(candidate=>candidate.id===project.space_id);const projectMember=projectSpace?members.find(candidate=>candidate.space_id===projectSpace.id&&candidate.user_id===userId):undefined;return spaceCategoryAccess(projectSpace,projectMember,'projects').canEdit}
 const [creating,setCreating]=useState(false),[name,setName]=useState(''),[description,setDescription]=useState(''),[target,setTarget]=useState('')
 const active=useMemo(()=>projects.filter(p=>p.status!=='archived'&&(!spaceId||p.space_id===spaceId)),[projects,spaceId])
 async function save(){if(!name.trim()||!canEdit)return;const p=await createProject({name,description,target_date:target||null,space_id:spaceId||null});setName('');setDescription('');setTarget('');setCreating(false);nav(`/projects/${p.id}`)}
 return <div className="page organizer-page"><header className="page-header"><div><span className="eyebrow">PROJECTS{space?` · ${space.name.toUpperCase()}`:''}</span><h1>Big things, broken into next actions.</h1><p>{space?`Projects shared inside ${space.name}.`:'Keep outcomes, tasks, appointments and notes connected without turning your life into project-management software.'}</p></div>{canEdit&&<button className="primary-button" onClick={()=>setCreating(v=>!v)}><Plus size={17}/>New project</button>}</header>
 {!expansionAvailable&&<div className="migration-banner"><strong>Organizer database upgrade needed.</strong><span>Run the current master schema repair in Supabase.</span></div>}
 {spaceId&&!canEdit&&<div className="permission-note prominent"><Lock size={16}/><span>You have view-only access to Projects in this Space.</span></div>}
 {creating&&canEdit&&<section className="panel-card create-project-card"><div className="form-stack"><label>Project name<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Renovate the bedroom"/></label><label>What does done look like?<textarea rows={3} value={description} onChange={e=>setDescription(e.target.value)} placeholder="A short outcome, not a giant plan."/></label><label>Target date (optional)<input type="date" value={target} onChange={e=>setTarget(e.target.value)}/></label><div className="row-actions"><button className="secondary-button" onClick={()=>setCreating(false)}>Cancel</button><button className="primary-button" disabled={!name.trim()} onClick={save}>Create project</button></div></div></section>}
 <div className="project-grid">{active.map(project=>{const p=projectProgress(project,items);return <article className="project-card" key={project.id}><button className="project-card-main" onClick={()=>nav(`/projects/${project.id}`)}><div className="project-icon"><FolderKanban/></div><div><div className="project-title-row"><strong>{project.name}</strong>{project.priority==='high'&&<span className="priority-dot"/>}</div><p>{project.description||'No description yet.'}</p></div><div className="progress-track"><span style={{width:`${p.percent}%`}}/></div><div className="project-meta"><span><Target size={14}/>{p.open} next</span><span>{p.percent}%</span>{project.target_date&&<span><CalendarDays size={14}/>{new Date(project.target_date+'T12:00:00').toLocaleDateString()}</span>}</div></button>{projectEditable(project)&&<button className="project-archive" onClick={()=>archiveProject(project.id)} aria-label={`Archive ${project.name}`}><Archive size={16}/></button>}</article>})}</div>
 {!active.length&&!creating&&<div className="empty-state large"><FolderKanban size={38}/><strong>No projects here yet.</strong><span>{space?(canEdit?`Create a project in ${space.name}.`:`No projects have been shared in ${space.name} yet.`):'Create one for anything that takes more than a single action.'}</span></div>}</div>
}
