import { ArrowLeft, CalendarDays, CheckCircle2, Edit3, Plus, Target } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { ItemCard } from '../components/ItemCard'
import { Modal } from '../components/Modal'
import { useAppData } from '../contexts/AppDataContext'
import { useAuth } from '../contexts/AuthContext'
import { useOrganizer } from '../contexts/OrganizerContext'
import { lifeIntentParser } from '../lib/parser'
import { projectProgress } from '../lib/organizer'
import { spaceCategoryAccess } from '../lib/spacePermissions'
import type { Priority, ProjectStatus } from '../types'

export default function ProjectPage(){
 const {id}=useParams(); const nav=useNavigate(); const {userId}=useAuth(); const {items,events,notes,spaces,members,createItem}=useAppData(); const {projects,updateProject}=useOrganizer(); const [quick,setQuick]=useState('')
 const project=projects.find(p=>p.id===id); const related=useMemo(()=>items.filter(i=>i.project_id===id&&i.status!=='dismissed'),[items,id]); const progress=project?projectProgress(project,items):{percent:0,open:0,total:0,completed:0}
 const [editing,setEditing]=useState(false),[editName,setEditName]=useState(''),[editDescription,setEditDescription]=useState(''),[editTarget,setEditTarget]=useState(''),[editPriority,setEditPriority]=useState<Priority>('normal'),[editStatus,setEditStatus]=useState<ProjectStatus>('active')
 if(!project)return <div className="page"><button className="text-button" onClick={()=>nav('/projects')}><ArrowLeft/>Projects</button><div className="empty-state large"><strong>Project not found.</strong></div></div>
 const currentProject=project
 const projectSpace=spaces.find(space=>space.id===currentProject.space_id); const projectMember=projectSpace?members.find(member=>member.space_id===projectSpace.id&&member.user_id===userId):undefined; const canEdit=spaceCategoryAccess(projectSpace,projectMember,'projects').canEdit
 async function add(){if(!quick.trim()||!canEdit)return;const parsed=lifeIntentParser.parse(quick);await createItem(parsed,quick,{project_id:currentProject.id,is_inbox:false,space_id:currentProject.space_id||null});setQuick('')}
 function startEdit(){setEditName(currentProject.name);setEditDescription(currentProject.description||'');setEditTarget(currentProject.target_date||'');setEditPriority(currentProject.priority);setEditStatus(currentProject.status);setEditing(true)}
 async function saveEdit(){if(!editName.trim())return;await updateProject(currentProject.id,{name:editName.trim(),description:editDescription.trim()||null,target_date:editTarget||null,priority:editPriority,status:editStatus});setEditing(false)}
 return <div className="page organizer-page"><button className="text-button back-link" onClick={()=>nav('/projects')}><ArrowLeft size={16}/>All projects</button><header className="project-hero"><div><span className="eyebrow">PROJECT</span><h1>{currentProject.name}</h1><p>{currentProject.description||'Add a clear outcome so Future You knows what finished means.'}</p>{canEdit&&<button className="mini-action project-edit-button" onClick={startEdit}><Edit3 size={14}/>Edit project</button>}</div><div className="project-health"><strong>{progress.percent}%</strong><span>{progress.completed} of {progress.total} actions complete</span></div></header>
 <div className="progress-track hero-progress"><span style={{width:`${progress.percent}%`}}/></div><div className="project-detail-grid"><section className="panel-card"><div className="section-heading"><div><span className="eyebrow">NEXT ACTIONS</span><h2>{progress.open} open</h2></div></div>{canEdit?<div className="quick-add-line"><input value={quick} onChange={e=>setQuick(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void add()}} placeholder="Add the next thing to do…"/><button onClick={add}><Plus/></button></div>:<div className="permission-note">View-only project access.</div>}<div className="item-stack">{related.filter(i=>i.status==='open').map(item=><ItemCard key={item.id} item={item}/>)}</div>{!progress.open&&<div className="empty-state"><CheckCircle2/><strong>No open actions.</strong><span>Add a next step or mark the project complete.</span></div>}</section>
 <aside className="project-side"><section className="panel-card"><span className="eyebrow">PROJECT DETAILS</span><label className="detail-field"><Target size={16}/>Status<select disabled={!canEdit} value={currentProject.status} onChange={e=>updateProject(currentProject.id,{status:e.target.value as ProjectStatus})}><option value="active">Active</option><option value="paused">Paused</option><option value="completed">Completed</option></select></label><label className="detail-field"><CalendarDays size={16}/>Target<input disabled={!canEdit} type="date" value={currentProject.target_date||''} onChange={e=>updateProject(currentProject.id,{target_date:e.target.value||null})}/></label></section>
 <section className="panel-card"><span className="eyebrow">CONNECTED</span><div className="connected-counts"><div><strong>{events.filter(e=>e.project_id===id).length}</strong><span>appointments</span></div><div><strong>{notes.filter(n=>n.project_id===id).length}</strong><span>notes</span></div><div><strong>{related.filter(i=>i.status==='completed').length}</strong><span>completed</span></div></div></section></aside></div>
 <Modal open={editing&&canEdit} onClose={()=>setEditing(false)} title="Edit project"><div className="form-stack"><label>Project name<input autoFocus value={editName} onChange={e=>setEditName(e.target.value)}/></label><label>Outcome / description<textarea rows={4} value={editDescription} onChange={e=>setEditDescription(e.target.value)}/></label><div className="two-col"><label>Status<select value={editStatus} onChange={e=>setEditStatus(e.target.value as ProjectStatus)}><option value="active">Active</option><option value="paused">Paused</option><option value="completed">Completed</option></select></label><label>Priority<select value={editPriority} onChange={e=>setEditPriority(e.target.value as Priority)}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option></select></label></div><label>Target date<input type="date" value={editTarget} onChange={e=>setEditTarget(e.target.value)}/></label><button className="primary-button" onClick={saveEdit} disabled={!editName.trim()}>Save changes</button></div></Modal></div>
}
