import { ArrowLeft, CalendarDays, CheckCircle2, Copy, FolderKanban, Link2, Pencil, ShoppingBasket, StickyNote, UserCog, UserPlus, Users } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Modal } from '../components/Modal'
import { useAppData } from '../contexts/AppDataContext'
import { useAuth } from '../contexts/AuthContext'
import { useOrganizer } from '../contexts/OrganizerContext'
import { DEFAULT_SPACE_PERMISSIONS, normalizeSpacePermissions, SPACE_PERMISSION_GROUPS } from '../lib/spacePermissions'
import type { SpaceMember, SpacePermissions } from '../types'

export default function SpacePage(){
  const {id}=useParams();const nav=useNavigate();const {userId,demo}=useAuth()
  const {spaces,members,items,events,notes,activity,createInvite,updateMemberAccess,updateSpace,collaborationAvailable}=useAppData()
  const {projects}=useOrganizer()
  const space=spaces.find(s=>s.id===id)
  const [inviteOpen,setInviteOpen]=useState(false),[email,setEmail]=useState(''),[inviteRole,setInviteRole]=useState<'member'|'admin'>('member'),[invitePermissions,setInvitePermissions]=useState<SpacePermissions>({...DEFAULT_SPACE_PERMISSIONS}),[inviteLink,setInviteLink]=useState(''),[inviteExpiry,setInviteExpiry]=useState(''),[inviteError,setInviteError]=useState(''),[inviteSaving,setInviteSaving]=useState(false)
  const [manageMember,setManageMember]=useState<SpaceMember|null>(null),[memberPermissions,setMemberPermissions]=useState<SpacePermissions>({...DEFAULT_SPACE_PERMISSIONS}),[memberRole,setMemberRole]=useState<'member'|'admin'>('member'),[memberError,setMemberError]=useState(''),[memberSaving,setMemberSaving]=useState(false)
  const [editOpen,setEditOpen]=useState(false),[spaceName,setSpaceName]=useState(space?.name||''),[spaceError,setSpaceError]=useState('')

  const spaceMembers=members.filter(m=>m.space_id===id);const me=spaceMembers.find(m=>m.user_id===userId)
  const canManage=space?.role==='owner'||space?.role==='admin'||me?.role==='owner'||me?.role==='admin'
  const myPermissions=canManage?normalizeSpacePermissions(DEFAULT_SPACE_PERMISSIONS):normalizeSpacePermissions(me?.permissions)
  const canInvite=!space?.is_personal&&(canManage||myPermissions.invite_members)
  const counts=useMemo(()=>({
    shopping:items.filter(item=>item.space_id===id&&item.type==='shopping'&&item.status==='open').length,
    tasks:items.filter(item=>item.space_id===id&&item.type!=='shopping'&&item.status==='open').length,
    calendar:events.filter(event=>event.space_id===id).length,
    notes:notes.filter(note=>note.space_id===id).length,
    projects:projects.filter(project=>project.space_id===id&&project.status!=='archived').length,
  }),[items,events,notes,projects,id])

  if(!space)return <div className="page"><button className="text-button" onClick={()=>nav('/spaces')}><ArrowLeft/>Spaces</button><div className="empty-state large"><strong>Space not found.</strong></div></div>
  const currentSpace=space

  const categories=[
    {key:'shopping',label:'Shopping',description:'Lists, product links and shared purchases.',Icon:ShoppingBasket,view:myPermissions.view_shopping,edit:myPermissions.edit_shopping,route:`/shopping?space=${id}`,count:counts.shopping},
    {key:'tasks',label:'Tasks & chores',description:'Shared actions, errands and reminders.',Icon:CheckCircle2,view:myPermissions.view_tasks,edit:myPermissions.edit_tasks,route:`/tasks?space=${id}`,count:counts.tasks},
    {key:'calendar',label:'Calendar',description:'Appointments and plans for this Space.',Icon:CalendarDays,view:myPermissions.view_calendar,edit:myPermissions.edit_calendar,route:`/planner?space=${id}`,count:counts.calendar},
    {key:'notes',label:'Thoughts & files',description:'Shared notes, references and captured memory.',Icon:StickyNote,view:myPermissions.view_notes,edit:myPermissions.edit_notes,route:`/thoughts?space=${id}`,count:counts.notes},
    {key:'projects',label:'Projects',description:'Shared outcomes and connected next actions.',Icon:FolderKanban,view:myPermissions.view_projects,edit:myPermissions.edit_projects,route:`/projects?space=${id}`,count:counts.projects},
  ]

  async function makeInvite(){if(!id)return;setInviteError('');setInviteSaving(true);try{const result=await createInvite(id,email.trim()||undefined,inviteRole,invitePermissions);setInviteLink(`${location.origin}/life/#/invite/${encodeURIComponent(result.token)}`);setInviteExpiry(result.expires_at)}catch(e){setInviteError(e instanceof Error?e.message:'Could not create invite.')}finally{setInviteSaving(false)}}
  function startManage(member:SpaceMember){setManageMember(member);setMemberPermissions(normalizeSpacePermissions(member.permissions));setMemberRole(member.role==='admin'?'admin':'member');setMemberError('')}
  function togglePermission(which:'invite'|'member',key:keyof SpacePermissions,checked:boolean){const setter=which==='invite'?setInvitePermissions:setMemberPermissions;setter(current=>{const next={...current,[key]:checked};for(const group of SPACE_PERMISSION_GROUPS){if(key===group.view&&!checked)next[group.edit]=false;if(key===group.edit&&checked)next[group.view]=true}return next})}
  async function saveMember(){if(!manageMember||!id)return;setMemberError('');setMemberSaving(true);try{await updateMemberAccess(id,manageMember.user_id,memberPermissions,memberRole);setManageMember(null)}catch(e){setMemberError(e instanceof Error?e.message:'Could not save access.')}finally{setMemberSaving(false)}}
  async function saveSpace(){if(!spaceName.trim())return;setSpaceError('');try{await updateSpace(currentSpace.id,{name:spaceName.trim()});setEditOpen(false)}catch(e){setSpaceError(e instanceof Error?e.message:'Could not rename this Space.')}}

  return <div className="page organizer-page space-hub-page"><button className="text-button back-link" onClick={()=>nav('/spaces')}><ArrowLeft size={16}/>All spaces</button>
    <header className="page-header"><div><span className="eyebrow">SHARED SPACE</span><h1>{currentSpace.name}</h1><p>People join this Space once. Their category permissions decide what they can see or change everywhere in JustGlance.</p></div><div className="header-actions">{canManage&&<button className="secondary-button" onClick={()=>{setSpaceName(currentSpace.name);setEditOpen(true)}}><Pencil size={16}/>Edit space</button>}{canInvite&&<button className="primary-button" onClick={()=>setInviteOpen(true)}><UserPlus size={17}/>Invite member</button>}</div></header>
    {!collaborationAvailable&&!demo&&<div className="migration-banner"><strong>Shared permissions need the current collaboration schema.</strong><span>Run the current master schema repair in Supabase.</span></div>}
    <div className="space-membership-explainer"><Users size={18}/><div><strong>One membership, category-level access.</strong><span>An invite never creates a separate shopping-only or task-only membership. It joins this entire Space, then permissions control Shopping, Tasks, Calendar, Thoughts/Files and Projects.</span></div></div>
    <div className="space-category-grid">{categories.map(category=><button key={category.key} className={`space-category-card ${category.view?'':'disabled'}`} disabled={!category.view} onClick={()=>category.view&&nav(category.route)}><span className="space-category-icon"><category.Icon/></span><span className="space-category-copy"><strong>{category.label}</strong><span>{category.description}</span><small>{category.view?(category.edit?'Can view & edit':'View only'):'No access'}</small></span><span className="space-category-count">{category.count}</span></button>)}</div>
    <div className="space-admin-grid"><section className="panel-card"><div className="section-heading inline"><div><span className="eyebrow">MEMBERS</span><h2>{spaceMembers.length} people</h2></div>{canInvite&&<button className="mini-action" onClick={()=>setInviteOpen(true)}><UserPlus size={15}/>Invite</button>}</div><div className="member-list">{spaceMembers.map(member=><div className="member-row member-row-manage" key={member.user_id}><span className="member-avatar">{(member.greeting_name||member.display_name||'M')[0].toUpperCase()}</span><span><b>{member.greeting_name||member.display_name}</b><small>{member.role}{member.user_id===userId?' · you':''}</small></span>{canManage&&member.role!=='owner'&&<button className="member-manage-button" onClick={()=>startManage(member)} aria-label={`Manage ${member.display_name}`}><UserCog size={15}/></button>}</div>)}</div></section>
      <section className="panel-card"><span className="eyebrow">RECENT ACTIVITY</span><div className="space-activity-list">{activity.filter(entry=>entry.space_id===id).slice(0,8).map(entry=><p key={entry.id}>{entry.actor_name||'Someone'} {entry.action} <b>{entry.entity_title}</b></p>)}{!activity.some(entry=>entry.space_id===id)&&<p className="muted-copy">Activity will appear here as members make changes.</p>}</div></section></div>

    <Modal open={editOpen} onClose={()=>setEditOpen(false)} title="Edit space"><div className="form-stack"><label>Space name<input autoFocus value={spaceName} onChange={e=>setSpaceName(e.target.value)}/></label>{spaceError&&<div className="form-message">{spaceError}</div>}<button className="primary-button" onClick={saveSpace} disabled={!spaceName.trim()}>Save changes</button></div></Modal>
    <Modal open={inviteOpen} onClose={()=>{setInviteOpen(false);setInviteLink('');setInviteExpiry('');setInviteError('')}} title={`Invite to ${currentSpace.name}`}><div className="form-stack">{!inviteLink?<><p className="modal-intro">This link joins the entire <b>{currentSpace.name}</b> Space. Choose which categories this person can view or edit.</p><label>Email (optional)<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="person@example.com"/></label>{(currentSpace.role==='owner'||me?.role==='owner')&&<label>Role<select value={inviteRole} onChange={e=>setInviteRole(e.target.value as 'member'|'admin')}><option value="member">Member</option><option value="admin">Admin</option></select></label>}<div className="permission-editor"><div className="permission-head"><strong>Category permissions</strong><span>View / change</span></div>{SPACE_PERMISSION_GROUPS.map(group=><div className="permission-row" key={group.key}><span>{group.label}</span><label><input type="checkbox" checked={invitePermissions[group.view]} onChange={e=>togglePermission('invite',group.view,e.target.checked)}/>View</label><label><input type="checkbox" checked={invitePermissions[group.edit]} onChange={e=>togglePermission('invite',group.edit,e.target.checked)}/>Edit</label></div>)}<div className="permission-row single"><span>Can create invite links</span><label><input type="checkbox" checked={invitePermissions.invite_members} onChange={e=>togglePermission('invite','invite_members',e.target.checked)}/>Allow</label></div></div><p className="muted">Leave email blank for a shareable link. Email-bound links only work for that signed-in email.</p>{inviteError&&<div className="form-message">{inviteError}</div>}<button className="primary-button" onClick={makeInvite} disabled={inviteSaving}><Link2 size={17}/>{inviteSaving?'Creating…':'Create invite link'}</button></>:<><label>Secure invite link<input value={inviteLink} readOnly/></label><button className="primary-button" onClick={async()=>{await navigator.clipboard.writeText(inviteLink)}}><Copy size={17}/>Copy link</button><p className="muted">Expires {inviteExpiry?new Date(inviteExpiry).toLocaleString():'in seven days'}. The raw token is only shown here; Supabase stores its hash.</p></>}</div></Modal>
    <Modal open={!!manageMember} onClose={()=>setManageMember(null)} title={manageMember?`Access for ${manageMember.greeting_name||manageMember.display_name}`:'Member access'}><div className="form-stack">{manageMember&&<>{(currentSpace.role==='owner'||me?.role==='owner')&&<label>Role<select value={memberRole} onChange={e=>setMemberRole(e.target.value as 'member'|'admin')}><option value="member">Member</option><option value="admin">Admin</option></select></label>}<div className="permission-editor"><div className="permission-head"><strong>Category permissions</strong><span>View / change</span></div>{SPACE_PERMISSION_GROUPS.map(group=><div className="permission-row" key={group.key}><span>{group.label}</span><label><input type="checkbox" checked={memberPermissions[group.view]} onChange={e=>togglePermission('member',group.view,e.target.checked)}/>View</label><label><input type="checkbox" checked={memberPermissions[group.edit]} onChange={e=>togglePermission('member',group.edit,e.target.checked)}/>Edit</label></div>)}<div className="permission-row single"><span>Can create invite links</span><label><input type="checkbox" checked={memberPermissions.invite_members} onChange={e=>togglePermission('member','invite_members',e.target.checked)}/>Allow</label></div></div>{memberError&&<div className="form-message">{memberError}</div>}<button className="primary-button" onClick={saveMember} disabled={memberSaving}>{memberSaving?'Saving…':'Save access'}</button></>}</div></Modal>
  </div>
}
