const $ = (sel, root=document) => root.querySelector(sel);
const DATA_BASE = window.WHATMOD_DATA_BASE || './content/';
async function loadJson(name){ const res = await fetch(`${DATA_BASE}${name}.json`, {cache:'no-store'}); if(!res.ok) throw new Error(`Could not load ${name}.json`); return res.json(); }
function rel(path=''){ const depth = window.WHATMOD_PAGE_DEPTH || 0; if(/^https?:|mailto:|#/.test(path)) return path; return `${'../'.repeat(depth)}${path.replace(/^\.\//,'')}`; }
function esc(v=''){ return String(v).replace(/[&<>"']/g, m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])); }
function para(v=''){ return esc(v).split('\n').filter(Boolean).map(x=>`<p>${x}</p>`).join(''); }
function setTheme(site){ const t=site.theme||{}; [['--accent',t.accent],['--accent2',t.accent2],['--bg',t.background],['--ink',t.ink]].forEach(([k,v])=>v&&document.documentElement.style.setProperty(k,v)); document.title=site.brand||'WhatMod'; }
function navHtml(site,nav){ return `<nav class="nav"><a class="brand" href="${rel('./')}"><span class="brand-mark">${esc(site.logoMark||'✦')}</span><span>${esc(site.brand||'WhatMod')}</span></a><div class="nav-links">${nav.map(n=>`<a href="${rel(n.href)}">${esc(n.label)}</a>`).join('')}</div></nav>`; }
function btn(b, fallback='ghost'){ return `<a class="btn ${esc(b.style||fallback)}" href="${rel(b.href||'#')}">${esc(b.label||'Link')}</a>`; }
function tagsHtml(tags=[]){return `<div class="tags">${tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div>`}
function projectCard(p){ const href=p.links?.[0]?.href||`apps/${p.slug}/`; return `<a class="project-card" href="${rel(href)}"><img src="${rel(p.image||'assets/project-whatdash.svg')}" alt="${esc(p.title)}"><div class="meta"><span class="status">${esc(p.status||'Project')}</span><span>→</span></div><h3>${esc(p.title)}</h3><p>${esc(p.summary)}</p>${tagsHtml(p.tags)}</a>`; }
function sectionHead(s){ return `<div class="section-head"><div><span class="eyebrow">${esc(s.eyebrow||'')}</span><h2>${esc(s.title||'')}</h2><p>${esc(s.text||'')}</p></div>${s.buttonLabel?btn({label:s.buttonLabel,href:s.buttonHref,style:'ghost'}):''}</div>`; }
function renderFeatures(s){ if(!s?.enabled) return ''; return `<section class="section wrap" id="features">${sectionHead(s)}<div class="feature-grid">${(s.cards||[]).map(c=>`<div class="soft-card"><div class="orb">✦</div><h3>${esc(c.title)}</h3><p>${esc(c.text)}</p></div>`).join('')}</div></section>`; }
function renderStats(s){ if(!s?.enabled) return ''; return `<section class="stats wrap">${(s.items||[]).map(x=>`<div class="stat"><strong>${esc(x.value)}</strong><span>${esc(x.label)}</span></div>`).join('')}</section>`; }
function renderAbout(s){ if(!s?.enabled) return ''; return `<section class="section wrap" id="about"><div class="about-card"><div><span class="eyebrow">${esc(s.eyebrow||'')}</span><h2>${esc(s.title||'')}</h2><p class="lead">${esc(s.text||'')}</p></div><div class="mini-list">${(s.bullets||[]).map(b=>`<div class="mini">${esc(b)}</div>`).join('')}</div></div></section>`; }
function renderContact(s){ if(!s?.enabled) return ''; return `<section class="section wrap" id="contact"><div class="contact-card"><span class="eyebrow">${esc(s.eyebrow||'')}</span><h2>${esc(s.title||'')}</h2><p class="lead">${esc(s.text||'')}</p><div class="cta-row">${(s.buttons||[]).map(b=>btn(b,b.style||'ghost')).join('')}</div></div></section>`; }
async function renderHome(){ const [site,nav,projects]=await Promise.all([loadJson('site'),loadJson('nav'),loadJson('projects')]); setTheme(site); const sec=site.sections||{}; $('#app').innerHTML=`${navHtml(site,nav)}<main><section class="hero wrap"><span class="bubble b1"></span><span class="bubble b2"></span><span class="bubble b3"></span><div class="hero-grid"><div><span class="pill">${esc(site.heroBadge||site.tagline||'')}</span><h1>${esc(site.headline||'')}</h1><p class="lead">${esc(site.subheadline||'')}</p><div class="cta-row">${btn(site.primaryCta||{label:'View Projects',href:'#projects'},'primary')}${btn(site.secondaryCta||{label:'About',href:'#about'},'ghost')}</div></div><div class="mascot-card"><img src="${rel(site.avatar||'assets/mascot.svg')}" alt="${esc(site.brand)} mascot"><div class="spark">${esc(site.heroNote||site.tagline||'')}</div></div></div></section>${renderStats(sec.stats)}${renderFeatures(sec.features)}${sec.projects?.enabled===false?'':`<section class="section wrap" id="projects">${sectionHead(sec.projects||{title:'Projects',text:''})}<div class="grid">${projects.map(projectCard).join('')}</div></section>`}${renderAbout(sec.about)}${renderContact(sec.contact)}</main><footer class="footer wrap">${esc(site.footer||'')}</footer>`; }
async function renderProject(slug){ const [site,nav,projects]=await Promise.all([loadJson('site'),loadJson('nav'),loadJson('projects')]); setTheme(site); const p=projects.find(x=>x.slug===slug)||projects[0]; document.title=`${p.title} | ${site.brand}`; $('#app').innerHTML=`${navHtml(site,nav)}<main class="wrap"><section class="page-hero"><span class="pill">${esc(p.status||'Project')}</span><h1>${esc(p.title)}</h1><p class="lead">${esc(p.summary)}</p></section><article class="page-card"><img src="${rel(p.image||'assets/project-whatdash.svg')}" alt="${esc(p.title)}" class="page-image">${para(p.details||p.summary)}${tagsHtml(p.tags)}<div class="cta-row">${(p.links||[]).map(l=>btn(l,'primary')).join('')}<a class="btn ghost" href="${rel('./')}#projects">Back to projects</a></div></article></main><footer class="footer wrap">${esc(site.footer||'')}</footer>`; }
async function renderPage(slug){ const [site,nav,pages]=await Promise.all([loadJson('site'),loadJson('nav'),loadJson('pages')]); setTheme(site); const p=pages.find(x=>x.slug===slug)||pages[0]; document.title=`${p.title} | ${site.brand}`; $('#app').innerHTML=`${navHtml(site,nav)}<main class="wrap"><section class="page-hero"><span class="pill">${esc(p.eyebrow||'Page')}</span><h1>${esc(p.title)}</h1><p class="lead">${esc(p.summary)}</p></section><article class="page-card">${para(p.body||'')}${(p.sections||[]).map(s=>`<div class="content-block"><h2>${esc(s.title)}</h2>${para(s.text)}</div>`).join('')}<div class="cta-row">${(p.links||[]).map(l=>btn(l,'primary')).join('')}<a class="btn ghost" href="${rel('./')}">Back home</a></div></article></main><footer class="footer wrap">${esc(site.footer||'')}</footer>`; }
(async()=>{ try{ if(window.WHATMOD_PROJECT_SLUG) await renderProject(window.WHATMOD_PROJECT_SLUG); else if(window.WHATMOD_PAGE_SLUG) await renderPage(window.WHATMOD_PAGE_SLUG); else await renderHome(); }catch(err){ $('#app').innerHTML=`<main class="wrap"><section class="page-hero"><h1>Site loading issue</h1><p class="lead">${esc(err.message)}</p></section></main>`; console.error(err); }})();
