window.CQ_CONFIG = {
  SUPABASE_URL: "https://YOUR-PROJECT.supabase.co",
  SUPABASE_PUBLISHABLE_KEY: "YOUR-PUBLISHABLE-OR-ANON-KEY",
  SUPABASE_ANON_KEY: "YOUR-PUBLISHABLE-OR-ANON-KEY",
  APP_ID: "connection-quest-engine-v4"
};
window.COMPAT_CONFIG = window.CQ_CONFIG;
