import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useMemo } from 'react';
import { ArrowRight, Inbox, Lightbulb, Sparkles } from 'lucide-react';
import { useAppData } from '../contexts/AppDataContext.js';
import { useOrganizer } from '../contexts/OrganizerContext.js';
import { ItemCard } from '../components/ItemCard.js';
export default function InboxPage() {
    const { items, notes, updateItem, createItem } = useAppData();
    const { projects } = useOrganizer();
    const inbox = useMemo(() => items.filter(i => i.status === 'open' && (i.is_inbox || (!i.due_date && !i.project_id && !i.place_id && !i.space_id))), [items]);
    const thoughts = notes.slice(0, 8);
    return _jsxs("div", { className: "page organizer-page", children: [_jsx("header", { className: "page-header", children: _jsxs("div", { children: [_jsx("span", { className: "eyebrow", children: "BRAIN DUMP" }), _jsx("h1", { children: "Put it here. Organize it later." }), _jsx("p", { children: "JustGlance keeps loose thoughts and unprocessed tasks together until you decide what they mean." })] }) }), _jsxs("div", { className: "split-layout", children: [_jsxs("section", { className: "panel-card", children: [_jsxs("div", { className: "section-heading", children: [_jsxs("div", { children: [_jsx("span", { className: "eyebrow", children: "UNPROCESSED" }), _jsxs("h2", { children: [_jsx(Inbox, { size: 20 }), " Inbox"] })] }), _jsx("span", { className: "count-pill", children: inbox.length })] }), _jsx("div", { className: "item-stack", children: inbox.map(item => _jsxs("div", { className: "triage-wrap", children: [_jsx(ItemCard, { item: item, compact: true }), _jsxs("div", { className: "triage-actions", children: [_jsxs("button", { onClick: () => updateItem(item.id, { is_inbox: false, focus_pin: true }), children: [_jsx(Sparkles, { size: 14 }), "Do soon"] }), _jsx("button", { onClick: () => updateItem(item.id, { is_inbox: false, defer_until: new Date(Date.now() + 7 * 86400000).toISOString() }), children: "Someday" }), projects[0] && _jsxs("button", { onClick: () => updateItem(item.id, { is_inbox: false, project_id: projects[0].id }), children: ["To ", projects[0].name] })] })] }, item.id)) }), !inbox.length && _jsxs("div", { className: "empty-state", children: [_jsx(Inbox, {}), _jsx("strong", { children: "Inbox zero." }), _jsx("span", { children: "Your brain can stop holding onto everything." })] })] }), _jsxs("section", { className: "panel-card", children: [_jsx("div", { className: "section-heading", children: _jsxs("div", { children: [_jsx("span", { className: "eyebrow", children: "RECENT THOUGHTS" }), _jsxs("h2", { children: [_jsx(Lightbulb, { size: 20 }), " Notes & ideas"] })] }) }), _jsx("div", { className: "thought-stack", children: thoughts.map(note => _jsxs("article", { className: "thought-card", children: [_jsx("strong", { children: note.title }), _jsx("p", { children: note.body }), _jsxs("button", { onClick: () => createItem({ type: 'task', title: note.title, priority: 'normal', tags: ['from-note'], confidence: 1 }, note.body, { description: note.body, is_inbox: true }), children: ["Turn into task ", _jsx(ArrowRight, { size: 14 })] })] }, note.id)) }), !thoughts.length && _jsxs("div", { className: "empty-state", children: [_jsx(Lightbulb, {}), _jsx("strong", { children: "No loose thoughts yet." }), _jsx("span", { children: "Use Capture and choose Remember." })] })] })] })] });
}
