import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Home, Plus, ShoppingBasket, UsersRound } from 'lucide-react';
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAppData } from '../contexts/AppDataContext.js';
import { useAuth } from '../contexts/AuthContext.js';
import { Modal } from '../components/Modal.js';
export default function SpacesPage() { const { spaces, items, createSpace } = useAppData(); const { user, demo } = useAuth(); const nav = useNavigate(); const [open, setOpen] = useState(false); const [name, setName] = useState(''); const [error, setError] = useState(''); async function save() { if (!name.trim())
    return; setError(''); try {
    await createSpace(name.trim());
    setName('');
    setOpen(false);
}
catch (e) {
    setError(e instanceof Error ? e.message : 'Could not create that space.');
} } return _jsxs("div", { className: "page", children: [_jsxs("header", { className: "page-header", children: [_jsxs("div", { children: [_jsx("span", { className: "eyebrow", children: "SPACES" }), _jsx("h1", { children: "Life is easier together." }), _jsx("p", { children: "Invite people to one shared Space, then choose which categories each member can view or edit." })] }), _jsxs("button", { className: "primary-button", onClick: () => setOpen(true), children: [_jsx(Plus, { size: 18 }), "New space"] })] }), _jsxs("div", { className: "account-status-card", children: [_jsx("strong", { children: demo ? 'Demo mode' : 'Signed in' }), _jsx("span", { children: demo ? 'Shared links are disabled in demo mode.' : user?.email || 'Supabase account' })] }), _jsxs("div", { className: "space-grid", children: [spaces.filter(s => s.name !== 'Personal').map(space => { const count = items.filter(i => i.space_id === space.id && i.status === 'open').length; const shop = items.filter(i => i.space_id === space.id && i.type === 'shopping' && i.status === 'open').length; return _jsxs("button", { className: "space-card", onClick: () => nav(`/spaces/${space.id}`), children: [_jsx("div", { className: "space-icon", children: _jsx(Home, {}) }), _jsxs("div", { children: [_jsx("h2", { children: space.name }), _jsxs("p", { children: [_jsx(UsersRound, { size: 15 }), " ", space.role || 'member', " \u00B7 ", count, " open"] }), shop > 0 && _jsxs("span", { className: "space-shopping", children: [_jsx(ShoppingBasket, { size: 14 }), shop, " shopping"] })] })] }, space.id); }), spaces.filter(s => s.name !== 'Personal').length === 0 && _jsxs("div", { className: "large-empty", children: [_jsx(UsersRound, {}), _jsx("h2", { children: "No shared spaces yet." }), _jsx("p", { children: "Create one for a household, relationship, trip, team, or anything you want to share." })] })] }), _jsx(Modal, { open: open, onClose: () => setOpen(false), title: "Create a shared space", children: _jsxs("div", { className: "form-stack", children: [_jsxs("label", { children: ["Space name", _jsx("input", { value: name, onChange: e => setName(e.target.value), placeholder: "Home", autoFocus: true })] }), error && _jsx("div", { className: "form-message", children: error }), _jsx("button", { className: "primary-button", onClick: save, disabled: !name.trim(), children: "Create space" })] }) })] }); }
